apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-deployment
spec:
  replicas: 2

  selector:
    matchLabels:
      app: bmi

  template:
    metadata:
      labels:
        app: bmi

    spec:
      containers:
        - name: bmi-container
          image: venkata465/bmi-image:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000
