name: Build and Deploy BMI App

 

on:

  push:

    branches:

      - main

 

jobs:

  build-deploy:

    runs-on: self-hosted

 

    steps:

      - name: Checkout Code

        uses: actions/checkout@v4

 

      - name: Login to Docker Hub

        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

 

      - name: Build Docker Image

        run: docker build -t venkata465/bmi-image:${{ github.run_number }} -t venkata465/bmi-image:latest .

 

      - name: Push Docker Image

        run: |

          docker push venkata465/bmi-image:${{ github.run_number }}

          docker push venkata465/bmi-image:latest

 

      - name: Apply Kubernetes Files

        run: |

          kubectl apply -f k8s/deployment.yaml

          kubectl apply -f k8s/service.yaml

 

      - name: Update Deployment Image

        run: kubectl set image deployment/bmi-deployment bmi-container=venkata465/bmi-image:${{ github.run_number }}

 

      - name: Wait for Rollout

        run: kubectl rollout status deployment/bmi-deployment